name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Generate JaCoCo report
        run: ./gradlew jacocoTestReport

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Publish JaCoCo Coverage Report
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage-results-path: build/reports/jacoco/test/jacocoTestReport.xml
          coverage-summary-path: jacoco-summary.md
          coverage-report-title: "JaCoCo Coverage Report"

